### ISSUE TITLE
confused between make files

### ISSUE THREAD

**Issue by DevX-Cipher** [SKGleba/psp2pm#2]
doesn't compile says there is no makefile2 when it is only fails when trying to build it to a vpk

make[2]: *** [CMakeFiles/PM_SWITCH.vpk] Error 255
make[1]: *** [CMakeFiles/PM_SWITCH.vpk.dir/all] Error 2

**Comment by SKGleba** [comment]
make sure that you have a compatible and working version of vitasdk (best older revision from around the date of release)

**Comment by DevX-Cipher** [comment]
I’ve tried 4 different ones it’s doesn’t compile
